server:
  port: ${PORT:8080}

spring:
  profiles:
    active: ${ENVIRONMENT:dev}
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
    locations:
      - classpath:db/migration

