
--INSERT PESSOA
INSERT INTO PUBLIC.TBL_PESSOA (NOME, TELEFONE, IDADE, SCORE, CIDADE, ESTADO, REGIAO, DATA_INCLUSAO) VALUES ('Fulano de Tal', '99 99999-9999', 99, 1000, 'Sao Paulo', 'SP', 'Sudeste', parsedatetime('01-01-2022', 'dd-MM-yyyy'));
--INSERT INTO PUBLIC.TBL_PESSOA VALUES ( 2, 'Sicrano de Tal', '99 88888-8888', 99, 100, 'Santa Catarina', 'SC', 'Sul', parsedatetime('01-01-2022', 'dd-MM-yyyy'));

--INSERT FAIXA SCORE
INSERT INTO PUBLIC.TBL_SCORE (DESCRICAO, INICIAL, FINAL) VALUES ('Insuficiente', 0, 200 );
INSERT INTO PUBLIC.TBL_SCORE (DESCRICAO, INICIAL, FINAL) VALUES ('Inaceitável', 201, 500 );
--INSERT INTO PUBLIC.TBL_SCORE VALUES ('Aceitável', 501, 700 );
--INSERT INTO PUBLIC.TBL_SCORE VALUES ('Recomendável', 701, 1000 );

--INSERT AFINIDADE
INSERT INTO PUBLIC.TBL_AFINIDADE (REGIAO) VALUES ('Norte' );
INSERT INTO PUBLIC.TBL_AFINIDADE (REGIAO) VALUES ('Nordeste' );
INSERT INTO PUBLIC.TBL_AFINIDADE (REGIAO) VALUES ('Centro-Oeste' );
--INSERT INTO PUBLIC.TBL_AFINIDADE (REGIAO) VALUES ('Sudeste' );
--INSERT INTO PUBLIC.TBL_AFINIDADE (REGIAO) VALUES ('Sul' );

--INSERT ESTADOS DA REGIAO NORTE
INSERT INTO PUBLIC.TBL_ESTADO (ID_AFINIDADE, DESC_ESTADO) VALUES ((SELECT ID FROM TBL_AFINIDADE WHERE REGIAO  = 'Norte'), 'AC');
INSERT INTO PUBLIC.TBL_ESTADO (ID_AFINIDADE, DESC_ESTADO) VALUES ((SELECT ID FROM TBL_AFINIDADE WHERE REGIAO  = 'Norte'), 'AP');
INSERT INTO PUBLIC.TBL_ESTADO (ID_AFINIDADE, DESC_ESTADO) VALUES ((SELECT ID FROM TBL_AFINIDADE WHERE REGIAO  = 'Norte'), 'AM');
INSERT INTO PUBLIC.TBL_ESTADO (ID_AFINIDADE, DESC_ESTADO) VALUES ((SELECT ID FROM TBL_AFINIDADE WHERE REGIAO  = 'Norte'), 'PA');
INSERT INTO PUBLIC.TBL_ESTADO (ID_AFINIDADE, DESC_ESTADO) VALUES ((SELECT ID FROM TBL_AFINIDADE WHERE REGIAO  = 'Norte'), 'RO');
INSERT INTO PUBLIC.TBL_ESTADO (ID_AFINIDADE, DESC_ESTADO) VALUES ((SELECT ID FROM TBL_AFINIDADE WHERE REGIAO  = 'Norte'), 'RR');
INSERT INTO PUBLIC.TBL_ESTADO (ID_AFINIDADE, DESC_ESTADO) VALUES ((SELECT ID FROM TBL_AFINIDADE WHERE REGIAO  = 'Norte'), 'TO');


--INSERT ESTADOS DA REGIAO NORDESTE
INSERT INTO PUBLIC.TBL_ESTADO (ID_AFINIDADE, DESC_ESTADO) VALUES ((SELECT ID FROM TBL_AFINIDADE WHERE REGIAO  = 'Nordeste'), 'AL');
INSERT INTO PUBLIC.TBL_ESTADO (ID_AFINIDADE, DESC_ESTADO) VALUES ((SELECT ID FROM TBL_AFINIDADE WHERE REGIAO  = 'Nordeste'), 'BA');
INSERT INTO PUBLIC.TBL_ESTADO (ID_AFINIDADE, DESC_ESTADO) VALUES ((SELECT ID FROM TBL_AFINIDADE WHERE REGIAO  = 'Nordeste'), 'CE');
INSERT INTO PUBLIC.TBL_ESTADO (ID_AFINIDADE, DESC_ESTADO) VALUES ((SELECT ID FROM TBL_AFINIDADE WHERE REGIAO  = 'Nordeste'), 'MA');
INSERT INTO PUBLIC.TBL_ESTADO (ID_AFINIDADE, DESC_ESTADO) VALUES ((SELECT ID FROM TBL_AFINIDADE WHERE REGIAO  = 'Nordeste'), 'PB');
INSERT INTO PUBLIC.TBL_ESTADO (ID_AFINIDADE, DESC_ESTADO) VALUES ((SELECT ID FROM TBL_AFINIDADE WHERE REGIAO  = 'Nordeste'), 'PI');
INSERT INTO PUBLIC.TBL_ESTADO (ID_AFINIDADE, DESC_ESTADO) VALUES ((SELECT ID FROM TBL_AFINIDADE WHERE REGIAO  = 'Nordeste'), 'PE');
INSERT INTO PUBLIC.TBL_ESTADO (ID_AFINIDADE, DESC_ESTADO) VALUES ((SELECT ID FROM TBL_AFINIDADE WHERE REGIAO  = 'Nordeste'), 'RN');
INSERT INTO PUBLIC.TBL_ESTADO (ID_AFINIDADE, DESC_ESTADO) VALUES ((SELECT ID FROM TBL_AFINIDADE WHERE REGIAO  = 'Nordeste'), 'SE');

--INSERT ESTADOS DA REGIAO CENTRO-OESTE
INSERT INTO PUBLIC.TBL_ESTADO (ID_AFINIDADE, DESC_ESTADO) VALUES ((SELECT ID FROM TBL_AFINIDADE WHERE REGIAO  = 'Centro-Oeste'), 'DF');
INSERT INTO PUBLIC.TBL_ESTADO (ID_AFINIDADE, DESC_ESTADO) VALUES ((SELECT ID FROM TBL_AFINIDADE WHERE REGIAO  = 'Centro-Oeste'), 'GO');
INSERT INTO PUBLIC.TBL_ESTADO (ID_AFINIDADE, DESC_ESTADO) VALUES ((SELECT ID FROM TBL_AFINIDADE WHERE REGIAO  = 'Centro-Oeste'), 'MT');
INSERT INTO PUBLIC.TBL_ESTADO (ID_AFINIDADE, DESC_ESTADO) VALUES ((SELECT ID FROM TBL_AFINIDADE WHERE REGIAO  = 'Centro-Oeste'), 'MS');


--INSERT ESTADOS DA REGIAO SUDESTE
--INSERT INTO PUBLIC.TBL_ESTADO (ID_AFINIDADE, DESC_ESTADO) VALUES ((SELECT ID FROM TBL_AFINIDADE WHERE REGIAO  = 'Sudeste'), 'ES');
--INSERT INTO PUBLIC.TBL_ESTADO (ID_AFINIDADE, DESC_ESTADO) VALUES ((SELECT ID FROM TBL_AFINIDADE WHERE REGIAO  = 'Sudeste'), 'MG');
--INSERT INTO PUBLIC.TBL_ESTADO (ID_AFINIDADE, DESC_ESTADO) VALUES ((SELECT ID FROM TBL_AFINIDADE WHERE REGIAO  = 'Sudeste'), 'RJ');
--INSERT INTO PUBLIC.TBL_ESTADO (ID_AFINIDADE, DESC_ESTADO) VALUES ((SELECT ID FROM TBL_AFINIDADE WHERE REGIAO  = 'Sudeste'), 'SP');

--INSERT ESTADOS DA REGIAO SUL
--INSERT INTO PUBLIC.TBL_ESTADO (ID_AFINIDADE, DESC_ESTADO) VALUES ((SELECT ID FROM TBL_AFINIDADE WHERE REGIAO  = 'Sul'), 'PR');
--INSERT INTO PUBLIC.TBL_ESTADO (ID_AFINIDADE, DESC_ESTADO) VALUES ((SELECT ID FROM TBL_AFINIDADE WHERE REGIAO  = 'Sul'), 'RS');
--INSERT INTO PUBLIC.TBL_ESTADO (ID_AFINIDADE, DESC_ESTADO) VALUES ((SELECT ID FROM TBL_AFINIDADE WHERE REGIAO  = 'Sul'), 'SC');
