
--INSERT PESSOA
INSERT INTO PUBLIC.TBL_PESSOA VALUES ( 1, 'Fulano de Tal', '99 99999-9999', 99, 1000, 'Sao Paulo', 'SP', 'Sudeste', parsedatetime('01-01-2022', 'dd-MM-yyyy'));
INSERT INTO PUBLIC.TBL_PESSOA VALUES ( 2, 'Sicrano de Tal', '99 88888-8888', 99, 100, 'Santa Catarina', 'SC', 'Sul', parsedatetime('01-01-2022', 'dd-MM-yyyy'));

--INSERT FAIXA SCORE
INSERT INTO PUBLIC.TBL_SCORE VALUES ( 1, 'Insuficiente', 0, 200 );
INSERT INTO PUBLIC.TBL_SCORE VALUES ( 2, 'Inaceitável', 201, 500 );
INSERT INTO PUBLIC.TBL_SCORE VALUES ( 3, 'Aceitável', 501, 700 );
INSERT INTO PUBLIC.TBL_SCORE VALUES ( 4, 'Recomendável', 701, 1000 );

--INSERT AFINIDADE
INSERT INTO PUBLIC.TBL_AFINIDADE VALUES ( 1, 'Norte' );
INSERT INTO PUBLIC.TBL_AFINIDADE VALUES ( 2, 'Nordeste' );
INSERT INTO PUBLIC.TBL_AFINIDADE VALUES ( 3, 'Centro-Oeste' );
INSERT INTO PUBLIC.TBL_AFINIDADE VALUES ( 4, 'Sudeste' );
--INSERT INTO PUBLIC.TBL_AFINIDADE VALUES ( 5, 'Sul' );

--INSERT ESTADOS DA REGIAO NORTE
INSERT INTO PUBLIC.TBL_ESTADO VALUES ( 1,  1, 'AC');
INSERT INTO PUBLIC.TBL_ESTADO VALUES ( 2,  1, 'AP');
INSERT INTO PUBLIC.TBL_ESTADO VALUES ( 3,  1, 'AM');
INSERT INTO PUBLIC.TBL_ESTADO VALUES ( 4,  1, 'PA');
INSERT INTO PUBLIC.TBL_ESTADO VALUES ( 5,  1, 'RO');
INSERT INTO PUBLIC.TBL_ESTADO VALUES ( 6,  1, 'RR');
INSERT INTO PUBLIC.TBL_ESTADO VALUES ( 7,  1, 'TO');


--INSERT ESTADOS DA REGIAO NORDESTE
INSERT INTO PUBLIC.TBL_ESTADO VALUES ( 8,  2, 'AL');
INSERT INTO PUBLIC.TBL_ESTADO VALUES ( 9,  2, 'BA');
INSERT INTO PUBLIC.TBL_ESTADO VALUES ( 10,  2, 'CE');
INSERT INTO PUBLIC.TBL_ESTADO VALUES ( 11,  2, 'MA');
INSERT INTO PUBLIC.TBL_ESTADO VALUES ( 12,  2, 'PB');
INSERT INTO PUBLIC.TBL_ESTADO VALUES ( 13,  2, 'PI');
INSERT INTO PUBLIC.TBL_ESTADO VALUES ( 14,  2, 'PE');
INSERT INTO PUBLIC.TBL_ESTADO VALUES ( 15,  2, 'RN');
INSERT INTO PUBLIC.TBL_ESTADO VALUES ( 16,  2, 'SE');

--INSERT ESTADOS DA REGIAO CENTRO-OESTE
INSERT INTO PUBLIC.TBL_ESTADO VALUES ( 17,  3, 'DF');
INSERT INTO PUBLIC.TBL_ESTADO VALUES ( 18,  3, 'GO');
INSERT INTO PUBLIC.TBL_ESTADO VALUES ( 19,  3, 'MT');
INSERT INTO PUBLIC.TBL_ESTADO VALUES ( 20,  3, 'MS');


--INSERT ESTADOS DA REGIAO SUDESTE
INSERT INTO PUBLIC.TBL_ESTADO VALUES ( 21,  4, 'ES');
INSERT INTO PUBLIC.TBL_ESTADO VALUES ( 22,  4, 'MG');
INSERT INTO PUBLIC.TBL_ESTADO VALUES ( 23,  4, 'RJ');
INSERT INTO PUBLIC.TBL_ESTADO VALUES ( 24,  4, 'SP');

--INSERT ESTADOS DA REGIAO SUL
--INSERT INTO PUBLIC.TBL_ESTADO VALUES ( 25,  5, 'PR');
--INSERT INTO PUBLIC.TBL_ESTADO VALUES ( 26,  5, 'RS');
--INSERT INTO PUBLIC.TBL_ESTADO VALUES ( 27,  5, 'SC');
